/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airBNB;

import airBNB.Helper.Auth;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Administrator
 */
public class Main extends javax.swing.JFrame {
    
    ResultSet rs=null;
    PreparedStatement pst=null;
    private Map<String, String> bundle;
    private ArrayList<Map<String, String>> properties;
    private Auth auth;

    /**
     * Creates new form login
     */
    
    public Main() {
        initComponents();
         
    }
    
    public Main(Map<String, String> bundle, Auth auth){
        this();
        this.name = bundle.get("username");
        Welcome.setText("Welcome: " +name);
        this.bundle = bundle;
        this.auth = auth;
        this.properties = new ArrayList<>();
        fetch();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        FrameClose = new javax.swing.JLabel();
        LogOut = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Welcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Manage = new java.awt.Button();
        Book = new java.awt.Button();
        Manage_Prop = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airBNB/logo.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 80));

        FrameClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FrameClose.setForeground(new java.awt.Color(255, 255, 255));
        FrameClose.setText("X");
        FrameClose.setName(""); // NOI18N
        FrameClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                FrameCloseMouseReleased(evt);
            }
        });
        jPanel1.add(FrameClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 20, 20));

        LogOut.setBackground(new java.awt.Color(102, 102, 255));
        LogOut.setFont(new java.awt.Font("DialogInput", 3, 18)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 255, 255));
        LogOut.setLabel("Log-Out");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        jPanel1.add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 170, 40));

        jList1.setBackground(new java.awt.Color(32, 33, 35));
        jList1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 750, 260));

        Welcome.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Welcome.setForeground(new java.awt.Color(255, 255, 255));
        Welcome.setText("Welcome: " +name);
        jPanel1.add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Booking's Available:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        Manage.setBackground(new java.awt.Color(102, 102, 255));
        Manage.setFont(new java.awt.Font("DialogInput", 3, 18)); // NOI18N
        Manage.setForeground(new java.awt.Color(255, 255, 255));
        Manage.setLabel("Manage Bookings");
        Manage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageActionPerformed(evt);
            }
        });
        jPanel1.add(Manage, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 180, 40));

        Book.setBackground(new java.awt.Color(102, 102, 255));
        Book.setFont(new java.awt.Font("DialogInput", 3, 18)); // NOI18N
        Book.setForeground(new java.awt.Color(255, 255, 255));
        Book.setLabel("Book Now");
        Book.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookMouseClicked(evt);
            }
        });
        Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookActionPerformed(evt);
            }
        });
        jPanel1.add(Book, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 180, 40));

        Manage_Prop.setBackground(new java.awt.Color(102, 102, 255));
        Manage_Prop.setFont(new java.awt.Font("DialogInput", 3, 18)); // NOI18N
        Manage_Prop.setForeground(new java.awt.Color(255, 255, 255));
        Manage_Prop.setLabel("Manage Properties");
        Manage_Prop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Manage_PropMouseClicked(evt);
            }
        });
        Manage_Prop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_PropActionPerformed(evt);
            }
        });
        jPanel1.add(Manage_Prop, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
  int xy;
  int xx;
  String name;
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
         xx = evt.getX();
         xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void FrameCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameCloseMouseReleased
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_FrameCloseMouseReleased

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        
        //not done properly.
        
        JOptionPane.showMessageDialog(null, "Logged-Out!", "InfoBox: Success", JOptionPane.INFORMATION_MESSAGE);
        dispose();
        LoginMain login = new LoginMain(auth);
        login.setVisible(true);
        
        
        

    }//GEN-LAST:event_LogOutActionPerformed

    private void fetch() {
        DefaultListModel m = new DefaultListModel();
        properties.clear();
        try{
            String q = "SELECT * FROM project.property where country='" + bundle.get("country") + "';";
            pst = auth.getConnection().prepareStatement(q);
            rs=pst.executeQuery();
            while(rs.next()){
                Map<String, String> temp = new HashMap<String, String>();
                temp.put("property_id", rs.getString("property_id"));
                temp.put("city", rs.getString("city"));
                temp.put("street", rs.getString("street"));
                temp.put("houseno", rs.getString("houseno"));
                temp.put("province", rs.getString("province"));
                temp.put("propertytype", rs.getString("propertytype"));
                temp.put("roomtype", rs.getString("roomtype"));
                temp.put("accommodates", rs.getString("accommodates"));
                temp.put("amenities", rs.getString("amenities"));
                temp.put("availabledate", rs.getString("availabledate"));
                temp.put("price", rs.getString("price"));
                temp.put("host_id", rs.getString("host_id"));
                temp.put("bathroom", rs.getString("bathroom"));
                temp.put("bedroom", rs.getString("bedroom"));
                temp.put("country", rs.getString("country"));
                
                properties.add(temp);
                
                String total = temp.get("houseno") +" "+ temp.get("street")+ ", " + temp.get("city") + ", " + temp.get("province")+ "     Price: "+ temp.get("price") + " per night"; 
                
                m.addElement(total);
            }
            jList1.setModel(m);
            
            pst.close();
            rs.close();
            
        }catch(NullPointerException | SQLException | ClassNotFoundException e){
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, e, null);
            // JOptionPane.showMessageDialog(null,e);
        }
    }
    private void ManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageActionPerformed
        // TODO add your handling code here:
        dispose();
        userBookings ub = new userBookings(bundle, auth);
        ub.setVisible(true);
    }//GEN-LAST:event_ManageActionPerformed

    private void BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookActionPerformed
        // TODO add your handling code here:
        int select = jList1.getSelectedIndex();
        
        
        if (select == -1){
            JOptionPane.showMessageDialog(null, "Select a Property to Book.", "InfoBox: Error", JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                Map<String, String> selectedProperty = properties.get(select);
                RentalAgreement ra = new RentalAgreement(bundle, selectedProperty, auth.getConnection());
                ra.setVisible(true);
            } catch(ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, ex, null);
            }
        }
        
       
    }//GEN-LAST:event_BookActionPerformed

    private void Manage_PropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_PropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Manage_PropActionPerformed

    private void Manage_PropMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Manage_PropMouseClicked
        // TODO add your handling code here:
        if(bundle.get("accounttype").equals("Single")) {
            JOptionPane.showMessageDialog(null, "Only Hosts can manage properties", "InfoBox: Access Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Fetching Properties", "InfoBox: Access Granted", JOptionPane.DEFAULT_OPTION);
            dispose();
            hostProperties hp = new hostProperties(bundle, auth);
            hp.setVisible(true);
        }
    }//GEN-LAST:event_Manage_PropMouseClicked

    private void BookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookMouseClicked
        // TODO add your handling code here:
        int index = jList1.getSelectedIndex();
        
        Logger.getLogger(Main.class.getName()).log(Level.INFO, String.valueOf(index), new Object[]{});
    }//GEN-LAST:event_BookMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        fetch();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Book;
    private javax.swing.JLabel FrameClose;
    private java.awt.Button LogOut;
    private java.awt.Button Manage;
    private java.awt.Button Manage_Prop;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
