/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airBNB;

import airBNB.Helper.Auth;
import java.util.Map;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.DefaultListModel;
/**
 *
 * @author Administrator
 */
public class userBookings extends javax.swing.JFrame {
    
    private Auth auth;
    private ArrayList<Map<String, String>> rentals;
    /**
     * Creates new form login
     */
    
    public userBookings() {
        initComponents();
    }
    
    public userBookings(Map<String, String> bundle, Auth auth){
        this();
        this.bundle = bundle;
        this.auth = auth;
        this.rentals = new ArrayList<>();
        fetch();
    }
    
    private void fetch() {
        DefaultListModel dm = new DefaultListModel();
        Statement st = null;
        rentals.clear();
        try{
            String id_sql = String.format("select distinct r.rentalagree_id, r.property_id,r.startdate,r.enddate, r.guest_id, p.houseno, p.street, p.city, p.country, p.price from project.rentalagreement r inner join "
                    + "project.property p on r.guest_id=(select guest_id from project.guest where user_id=%s) and p.property_id=r.property_id", bundle.get("id"));
            st = auth.getConnection().createStatement();
            ResultSet rs = st.executeQuery(id_sql);
            while(rs.next()) {
                Map<String, String> temp = new HashMap<>();
 
                temp.put("rentalagree_id", rs.getString("rentalagree_id"));
                temp.put("property_id", rs.getString("property_id"));
                temp.put("startdate", rs.getString("startdate"));
                temp.put("enddate", rs.getString("enddate"));
                temp.put("guest_id", rs.getString("guest_id"));
                temp.put("houseno", rs.getString("houseno"));
                temp.put("street", rs.getString("street"));
                temp.put("city", rs.getString("city"));
                temp.put("country", rs.getString("country"));
                temp.put("price", rs.getString("price"))
                        ;
                rentals.add(temp);
                String disp = temp.get("houseno") + " " + temp.get("street") + " " + temp.get("city") + " " + temp.get("price") + "per night";
                dm.addElement(disp);
            }
            st.close();
            rs.close();
            jList1.setModel(dm);
        }catch(ClassNotFoundException | SQLException ex) {
            Logger.getLogger(userBookings.class.getName()).log(Level.SEVERE, ex, null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        FrameClose = new javax.swing.JLabel();
        LogOut = new java.awt.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        Manage = new java.awt.Button();
        LogOut1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airBNB/logo.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 80));

        FrameClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FrameClose.setForeground(new java.awt.Color(255, 255, 255));
        FrameClose.setText("X");
        FrameClose.setName(""); // NOI18N
        FrameClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                FrameCloseMouseReleased(evt);
            }
        });
        jPanel1.add(FrameClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 20, 20));

        LogOut.setBackground(new java.awt.Color(102, 102, 255));
        LogOut.setFont(new java.awt.Font("DialogInput", 3, 18)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 255, 255));
        LogOut.setLabel("Log-Out");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        jPanel1.add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 170, 40));

        jList1.setBackground(new java.awt.Color(32, 33, 35));
        jList1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 610, 260));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Your Bookings:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        Manage.setBackground(new java.awt.Color(102, 102, 255));
        Manage.setFont(new java.awt.Font("DialogInput", 3, 18)); // NOI18N
        Manage.setForeground(new java.awt.Color(255, 255, 255));
        Manage.setLabel("Booking Information");
        Manage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageActionPerformed(evt);
            }
        });
        jPanel1.add(Manage, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 230, 40));

        LogOut1.setBackground(new java.awt.Color(102, 102, 255));
        LogOut1.setFont(new java.awt.Font("DialogInput", 3, 18)); // NOI18N
        LogOut1.setForeground(new java.awt.Color(255, 255, 255));
        LogOut1.setLabel("<- Go Back");
        LogOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut1ActionPerformed(evt);
            }
        });
        jPanel1.add(LogOut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 170, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
  int xy;
  int xx;
  Map<String, String> bundle;
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
         xx = evt.getX();
         xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void FrameCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrameCloseMouseReleased
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_FrameCloseMouseReleased

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        
        //not done properly.
        
        JOptionPane.showMessageDialog(null, "Logged-Out!", "InfoBox: Success", JOptionPane.INFORMATION_MESSAGE);
        dispose();
        LoginMain login = new LoginMain(auth);
        login.setVisible(true);
        
        
        

    }//GEN-LAST:event_LogOutActionPerformed

    private void ManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageActionPerformed
        // TODO add your handling code here:
        int select = jList1.getSelectedIndex();
         if (select == -1){
            JOptionPane.showMessageDialog(null, "Select a Booking.", "InfoBox: Error", JOptionPane.INFORMATION_MESSAGE);
        }else{
            Map<String, String> rental = rentals.get(select);
            try {
                PropInfo pi = new PropInfo(bundle, rental, auth.getConnection());
                pi.setVisible(true);
            } catch(ClassNotFoundException | SQLException ex) {
                Logger.getLogger(userBookings.class.getName()).log(Level.SEVERE, ex, null);
            }
         }
    }//GEN-LAST:event_ManageActionPerformed

    private void LogOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOut1ActionPerformed
        // TODO add your handling code here:
        dispose();
        Main  m = new Main(bundle, auth);
        m.setVisible(true);
    }//GEN-LAST:event_LogOut1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userBookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FrameClose;
    private java.awt.Button LogOut;
    private java.awt.Button LogOut1;
    private java.awt.Button Manage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
